[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
todo_list_app = "DMHCivUmzPmMiHhsjPkK6HsZjSbmgcTcaE2i4zM4atRK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/baoanh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
